Configure active job adapter for test suite
Trying to avoid this:
  ArgumentError: assert_enqueued_with requires the Active Job test
  adapter, you're using ActiveJob::QueueAdapters::DelayedJobAdapter.

Not entirely sure why, but this became needed after 7.1 -> 7.2 rails
upgrade done in previous commit.