Quickfix for errors serving encrypted TiddlyWikis
Avoid a NoMethodError (undefined method `xpath' for nil:NilClass)
because div#storeArea isn't there.

Issue #67.